Repository osbdr/pipeline-django-semver-demo, pull requests merged in 2020-08, with the labels that each got.

#27 chore(deps): update dependency django to v3.0.9
  requirements.txt
Labels: renovate

#28 chore(deps): update dependency django to v3.1
  requirements.txt
Labels: renovate

#29 chore(deps): update dependency isort to v5.3.0
  requirements.txt
Labels: renovate

#31 chore(deps): update dependency django-extensions to v3.0.4
  requirements.txt
Labels: renovate

#32 chore(deps): update dependency isort to v5.3.2
  requirements.txt
Labels: renovate

#34 chore(deps): update dependency django-extensions to v3.0.5
  requirements.txt
Labels: renovate

#38 docs: german to english translation
  README.md
Labels: documentation

#41 chore(deps): update dependency isort to v5.4.2
  requirements.txt
Labels: bug, documentation, renovate
